version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn test # Make sure this command generates the coverage report
      - persist_to_workspace:
          root: . # This will save the entire working directory
          paths:
            - target # Adjust if your path is different

  upload-coverage:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace: # This retrieves the workspace saved by the previous job
          at: /tmp/workspace
      - codecov/upload:
          path: /tmp/workspace/target/site/jacoco # Update the path to where your report is stored

workflows:
  version: 2
  build-and-test-and-upload:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - upload-coverage:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
