version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - target

  upload-coverage:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - codecov/upload:

workflows:
  version: 2
  build-and-test-and-upload:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - upload-coverage:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
