version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: target/my-report

  upload-coverage:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - codecov/upload

workflows:
  version: 2
  build-and-test-on-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
      - upload-coverage:
          filters:
            branches:
              only: master