version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Maven Test and generate coverage report
          command: mvn test
      - persist_to_workspace:  # This will make the coverage reports available to the next job
          root: .
          paths:
            - target/site/jacoco/  # Adjust the path to where your coverage reports are generated

workflows:
  version: 2
  complete-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - codecov/upload:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
