version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn compile

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test

  upload-to-codecov:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: "Tests with JaCoCo coverage"
          command: mvn clean verify jacoco:report
      - codecov/upload

  generate-javadoc:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

  deploy-to-gh-pages:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config --global user.email "isfurtado@hotmail.com"
            git config --global user.name "ingridsimoes"
            # A inclusão do token de acesso pessoal para autenticação no GitHub
            git clone https://x-access-token:${GH_TOKEN}@github.com/ingridsimoes/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages
            git checkout --orphan gh-pages  # Cria a branch gh-pages como uma branch órfã se ela não existir
            git rm -rf .
            cp -r ../path/to/generated/docs/* .
            git add .
            git commit -m "Update GitHub Pages documentation"
            git push -u origin gh-pages


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
      - upload-to-codecov:
          requires:
            - test
      - generate-javadoc:
          requires:
            - test
      - deploy-to-gh-pages:
          requires:
            - generate-javadoc
          filters:
            branches:
              only:
                - main
